name: PUBLISH
on: [push]

jobs:
    deploy:
          runs-on: ubuntu-latest
          steps:
               - name: Fetch
                 uses: actions/checkout@v3
               - name: SSH_EC2
                 uses: appleboy/ssh-action@master
                 with:
                    host: 3.88.208.120
                    key: ${{secrets.BRANCH}}
                    username: ubuntu
                    port: 22
                    script: |
                         sudo apt install nodejs
                         sudo apt install npm
                         git clone https://github.com/acs-web-tech/PEARLTHOUGHTSREPO.git
                         cd PEARLTHOUGHTSREPO
                         npm -g install pm2
                         sudo pm2 start index.js
                    
          
                          
